/* Copyright 2025-2026 Eugene Petrenko (mcp@jonnyzzz.com); Copyright 2025-2026 JetBrains. Use of this source code is governed by the Apache 2.0 license. */
package com.jonnyzzz.mcpSteroid.devrig

import com.jonnyzzz.mcpSteroid.testHelper.ProjectHomeDirectory
import java.io.File
import java.nio.file.Files
import java.nio.file.Path
import kotlin.io.path.exists
import kotlin.io.path.readText
import kotlin.test.AfterTest
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertFalse
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertDoesNotThrow
import org.junit.jupiter.api.io.TempDir

class BinLauncherTest {
    @TempDir
    lateinit var tmp: Path

    private val home: HomePaths get() = HomePaths(tmp.resolve(".mcp-steroid"))

    // devrig's installed root (content-addressed) + the JDK, both UNDER ~/.mcp-steroid so the
    // self-register guard fires and relToHome succeeds.
    private val ownRoot: Path get() = home.home.resolve("binaries").resolve("devrig-linux-x64-1.2.3-abc").resolve("devrig-1.2.3")
    private val ownJava: Path get() = home.home.resolve("binaries").resolve("jdk-linux-x64-1.2.3-def").resolve("jdk")
    private val userHome: Path get() = tmp

    @AfterTest
    fun resetDevrigRoot() = DevrigRootTestSupport.reset()

    // ── pure render functions (byte-exact copies of the installer templates) ──

    @Test
    fun `renderPosixLauncher is byte-exact`() {
        val expected = buildString {
            append("#!/bin/sh\n")
            append("# devrig launcher — generated by install.sh. Writes nothing to stdout (MCP stdio channel).\n")
            append("# Always pins the bundled JDK via DEVRIG_JAVA_HOME (the bundled runtime is the supported one),\n")
            append("# then hands off to the devrig binary.\n")
            append("DEVRIG_JAVA_HOME=\"\$HOME/.mcp-steroid/binaries/jdk/jdk\"; export DEVRIG_JAVA_HOME\n")
            append("exec \"\$HOME/.mcp-steroid/binaries/devrig/bin/devrig\" \"\$@\"\n")
        }
        assertEquals(
            expected,
            renderPosixLauncher(".mcp-steroid/binaries/devrig/bin/devrig", ".mcp-steroid/binaries/jdk/jdk"),
        )
    }

    @Test
    fun `renderWindowsCmd is byte-exact (full batch launcher, no powershell)`() {
        assertEquals(
            "@echo off\r\n" +
                "set \"DEVRIG_JAVA_HOME=%USERPROFILE%\\j\\jdk\"\r\n" +
                "call \"%USERPROFILE%\\d\\devrig.bat\" %*\r\n",
            renderWindowsCmd("d\\devrig.bat", "j\\jdk"),
        )
    }

    // ── relToHome ──

    @Test
    fun `relToHome strips the home prefix and rejects escaping paths`() {
        assertEquals(
            "a/b/c".replace('/', File.separatorChar),
            relToHome(tmp, tmp.resolve("a").resolve("b").resolve("c")),
        )
        assertFailsWith<IllegalArgumentException> { relToHome(tmp.resolve("home"), tmp.resolve("elsewhere").resolve("x")) }
    }

    // ── normalizeLauncher ──

    @Test
    fun `normalizeLauncher tolerates CRLF and trailing newlines but not real changes`() {
        assertEquals(normalizeLauncher("a\r\nb\n"), normalizeLauncher("a\nb\n\n\n"))
        assertTrue(normalizeLauncher("a\nb") != normalizeLauncher("a\nB"))
    }

    // ── ensureBinLauncher core (POSIX) ──

    @Test
    fun `posix launcher is created executable with the expected content`() {
        ensureBinLauncher(home, isWin = false, ownRoot = ownRoot, ownJava = ownJava, userHome = userHome)
        val target = home.binDir.resolve("devrig")
        assertTrue(target.exists(), "launcher not created")
        assertEquals(
            renderPosixLauncher(relToHome(userHome, ownRoot.resolve("bin").resolve("devrig")), relToHome(userHome, ownJava)),
            target.readText(),
        )
        assertTrue(Files.isExecutable(target), "launcher must be executable")
    }

    @Test
    fun `re-run does not rewrite when content is normalize-equivalent`() {
        ensureBinLauncher(home, isWin = false, ownRoot = ownRoot, ownJava = ownJava, userHome = userHome)
        val target = home.binDir.resolve("devrig")
        // Overwrite with a normalize-equivalent variant (extra trailing newlines); a second run must skip it.
        val variant = target.readText() + "\n\n"
        Files.writeString(target, variant)
        ensureBinLauncher(home, isWin = false, ownRoot = ownRoot, ownJava = ownJava, userHome = userHome)
        assertEquals(variant, target.readText(), "must not rewrite when only trailing newlines differ")
    }

    @Test
    fun `stale launcher is rewritten to the current location`() {
        val target = home.binDir.resolve("devrig")
        Files.createDirectories(home.binDir)
        Files.writeString(target, "#!/bin/sh\nexec \"\$HOME/old/path/devrig\" \"\$@\"\n")
        ensureBinLauncher(home, isWin = false, ownRoot = ownRoot, ownJava = ownJava, userHome = userHome)
        assertTrue(target.readText().contains("binaries/devrig-linux-x64-1.2.3-abc/devrig-1.2.3/bin/devrig"))
    }

    @Test
    fun `missing launcher is recreated`() {
        ensureBinLauncher(home, isWin = false, ownRoot = ownRoot, ownJava = ownJava, userHome = userHome)
        val target = home.binDir.resolve("devrig")
        Files.delete(target)
        ensureBinLauncher(home, isWin = false, ownRoot = ownRoot, ownJava = ownJava, userHome = userHome)
        assertTrue(target.exists())
    }

    // ── ensureBinLauncher core (Windows) ──

    @Test
    fun `windows writes devrig_cmd only (no devrig_ps1, no posix launcher)`() {
        ensureBinLauncher(home, isWin = true, ownRoot = ownRoot, ownJava = ownJava, userHome = userHome)
        val cmd = home.binDir.resolve("devrig.cmd")
        assertTrue(cmd.exists(), "devrig.cmd must be written")
        assertTrue(cmd.readText().contains("DEVRIG_JAVA_HOME"))
        assertTrue(cmd.readText().contains("devrig.bat"), "inner launcher must be devrig.bat on Windows")
        assertEquals(
            renderWindowsCmd(relToHome(userHome, ownRoot.resolve("bin").resolve("devrig.bat")), relToHome(userHome, ownJava)),
            cmd.readText(),
        )
        assertFalse(home.binDir.resolve("devrig.ps1").exists(), "launcher is CMD-only — no devrig.ps1")
        assertFalse(home.binDir.resolve("devrig").exists(), "no POSIX launcher on the Windows branch")
    }

    @Test
    fun `windows self-heal removes an orphan devrig_ps1 from an older install`() {
        Files.createDirectories(home.binDir)
        Files.writeString(home.binDir.resolve("devrig.ps1"), "# old powershell launcher\n")
        ensureBinLauncher(home, isWin = true, ownRoot = ownRoot, ownJava = ownJava, userHome = userHome)
        assertFalse(home.binDir.resolve("devrig.ps1").exists(), "obsolete devrig.ps1 must be removed")
        assertTrue(home.binDir.resolve("devrig.cmd").exists())
    }

    // ── guard: do not repoint the launcher when running from a build tree (not under ~/.mcp-steroid) ──

    @Test
    fun `does not self-register when devrig root is outside the mcp-steroid home`() {
        val buildTreeRoot = tmp.resolve("repo").resolve("npx-kt").resolve("build").resolve("install").resolve("devrig")
        ensureBinLauncher(home, isWin = false, ownRoot = buildTreeRoot, ownJava = ownJava, userHome = userHome)
        assertFalse(home.binDir.resolve("devrig").exists(), "build-tree runs must not write a launcher")
    }

    // ── public entry point is best-effort: never throws even when DevrigRoot cannot resolve ──

    @Test
    fun `public ensureBinLauncher never throws when the devrig root is unresolvable`() {
        // Force DevrigRoot.path to throw deterministically: a code-source with no lib/+ij-plugin.zip ancestor.
        DevrigRootTestSupport.overrideCodeSource(tmp.resolve("no-installdist").resolve("classes"))
        assertDoesNotThrow { ensureBinLauncher(home) }
        assertFalse(home.binDir.resolve("devrig").exists(), "nothing should be written when the root is unresolvable")
    }

    // ── cross-module drift guard: the renderers must stay byte-identical (modulo line endings) to the
    //    launcher bodies the generated install.sh / install.ps1 actually write (site-gen templates),
    //    else a fresh install + self-heal would rewrite on every launch. ──

    @Test
    fun `renderPosixLauncher matches the install_sh_tmpl heredoc body`() {
        val tmpl = ProjectHomeDirectory.requireProjectHomeDirectory().resolve("site-gen/src/main/resources/templates/install.sh.tmpl").readText()
        val start = tmpl.indexOf("<<EOF\n") + "<<EOF\n".length
        val end = tmpl.indexOf("\nEOF", start)
        require(start > 5 && end > start) { "could not locate the launcher heredoc in install.sh.tmpl" }
        val jdk = "REL/jdk-home"
        val launcher = "REL/bin/devrig"
        // Emulate the unquoted-heredoc expansion: install.sh shell-expands ${jdk_home_rel}/${launcher_rel};
        // \$ becomes a literal $ in the written file.
        val expanded = tmpl.substring(start, end + 1)
            .replace("\${jdk_home_rel}", jdk)
            .replace("\${launcher_rel}", launcher)
            .replace("\\\$", "\$")
        assertEquals(normalizeLauncher(renderPosixLauncher(launcher, jdk)), normalizeLauncher(expanded))
    }

    @Test
    fun `renderWindowsCmd matches the install_ps1_tmpl devrig_cmd body`() {
        val tmpl = ProjectHomeDirectory.requireProjectHomeDirectory().resolve("site-gen/src/main/resources/templates/install.ps1.tmpl").readText()
        val jdk = "REL\\jdk-home"
        val launcher = "REL\\bin\\devrig.bat"

        // The install.ps1 builds devrig.cmd via the $cmd = "..." line: decode `r`n -> CRLF and `" -> ",
        // then substitute the PowerShell-interpolated $jdkHomeRel / $launcherRel with test values.
        val cmdLine = tmpl.lines().first { it.trimStart().startsWith("\$cmd = ") }
        val cmdDecoded = cmdLine.substringAfter("\"").substringBeforeLast("\"")
            .replace("`r`n", "\n")
            .replace("`\"", "\"")
            .replace("\$jdkHomeRel", jdk)
            .replace("\$launcherRel", launcher)
        assertEquals(normalizeLauncher(renderWindowsCmd(launcher, jdk)), normalizeLauncher(cmdDecoded))
    }

}
