/* Copyright 2025-2026 Eugene Petrenko (mcp@jonnyzzz.com); Copyright 2025-2026 JetBrains. Use of this source code is governed by the Apache 2.0 license. */
package com.jonnyzzz.mcpSteroid.devrig

import java.io.File
import java.nio.file.Files
import java.nio.file.Path
import kotlin.io.path.exists
import kotlin.io.path.readText
import kotlin.test.AfterTest
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertFalse
import kotlin.test.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertDoesNotThrow
import org.junit.jupiter.api.io.TempDir

class BinLauncherTest {
    @TempDir
    lateinit var tmp: Path

    private val home: HomePaths get() = HomePaths(tmp.resolve(".mcp-steroid"))

    // devrig's installed root (content-addressed) + the JDK, both UNDER ~/.mcp-steroid so the
    // self-register guard fires and relToHome succeeds.
    private val ownRoot: Path get() = home.home.resolve("binaries").resolve("devrig-linux-x64-1.2.3-abc").resolve("devrig-1.2.3")
    private val ownJava: Path get() = home.home.resolve("binaries").resolve("jdk-linux-x64-1.2.3-def").resolve("jdk")
    private val userHome: Path get() = tmp

    @AfterTest
    fun resetDevrigRoot() = DevrigRootTestSupport.reset()

    // ── pure render functions (byte-exact copies of the installer templates) ──

    @Test
    fun `renderPosixLauncher is byte-exact`() {
        val expected = buildString {
            append("#!/bin/sh\n")
            append("# devrig launcher — generated by install.sh. Writes nothing to stdout (MCP stdio channel).\n")
            append("# Sets DEVRIG_JAVA_HOME (honored by the devrig launcher) to the bundled JDK unless the user\n")
            append("# already provided one, then hands off to the devrig binary.\n")
            append("if [ -z \"\${DEVRIG_JAVA_HOME:-}\" ]; then\n")
            append("  DEVRIG_JAVA_HOME=\"\$HOME/.mcp-steroid/binaries/jdk/jdk\"; export DEVRIG_JAVA_HOME\n")
            append("fi\n")
            append("exec \"\$HOME/.mcp-steroid/binaries/devrig/bin/devrig\" \"\$@\"\n")
        }
        assertEquals(
            expected,
            renderPosixLauncher(".mcp-steroid/binaries/devrig/bin/devrig", ".mcp-steroid/binaries/jdk/jdk"),
        )
    }

    @Test
    fun `renderWindowsPs1 and renderWindowsCmd are byte-exact`() {
        val ps1 = buildString {
            append("# devrig launcher — generated by install.ps1. Writes nothing to stdout (MCP stdio channel).\n")
            append("# Sets DEVRIG_JAVA_HOME (honored by the devrig launcher) to the bundled JDK unless already set.\n")
            append("\$root = \$env:USERPROFILE; if (-not \$root) { \$root = \$env:HOME }\n")
            append("if (-not \$env:DEVRIG_JAVA_HOME) { \$env:DEVRIG_JAVA_HOME = Join-Path \$root 'j\\jdk' }\n")
            append("& (Join-Path \$root 'd\\devrig.bat') @args\n")
            append("exit \$LASTEXITCODE\n")
        }
        assertEquals(ps1, renderWindowsPs1("d\\devrig.bat", "j\\jdk"))
        assertEquals(
            "@echo off\r\npowershell.exe -NoProfile -ExecutionPolicy Bypass -File \"%~dp0devrig.ps1\" %*\r\n",
            renderWindowsCmd(),
        )
    }

    // ── relToHome ──

    @Test
    fun `relToHome strips the home prefix and rejects escaping paths`() {
        assertEquals(
            "a/b/c".replace('/', File.separatorChar),
            relToHome(tmp, tmp.resolve("a").resolve("b").resolve("c")),
        )
        assertFailsWith<IllegalArgumentException> { relToHome(tmp.resolve("home"), tmp.resolve("elsewhere").resolve("x")) }
    }

    // ── normalizeLauncher ──

    @Test
    fun `normalizeLauncher tolerates CRLF and trailing newlines but not real changes`() {
        assertEquals(normalizeLauncher("a\r\nb\n"), normalizeLauncher("a\nb\n\n\n"))
        assertTrue(normalizeLauncher("a\nb") != normalizeLauncher("a\nB"))
    }

    // ── ensureBinLauncher core (POSIX) ──

    @Test
    fun `posix launcher is created executable with the expected content`() {
        ensureBinLauncher(home, isWin = false, ownRoot = ownRoot, ownJava = ownJava, userHome = userHome)
        val target = home.binDir.resolve("devrig")
        assertTrue(target.exists(), "launcher not created")
        assertEquals(
            renderPosixLauncher(relToHome(userHome, ownRoot.resolve("bin").resolve("devrig")), relToHome(userHome, ownJava)),
            target.readText(),
        )
        assertTrue(Files.isExecutable(target), "launcher must be executable")
    }

    @Test
    fun `re-run does not rewrite when content is normalize-equivalent`() {
        ensureBinLauncher(home, isWin = false, ownRoot = ownRoot, ownJava = ownJava, userHome = userHome)
        val target = home.binDir.resolve("devrig")
        // Overwrite with a normalize-equivalent variant (extra trailing newlines); a second run must skip it.
        val variant = target.readText() + "\n\n"
        Files.writeString(target, variant)
        ensureBinLauncher(home, isWin = false, ownRoot = ownRoot, ownJava = ownJava, userHome = userHome)
        assertEquals(variant, target.readText(), "must not rewrite when only trailing newlines differ")
    }

    @Test
    fun `stale launcher is rewritten to the current location`() {
        val target = home.binDir.resolve("devrig")
        Files.createDirectories(home.binDir)
        Files.writeString(target, "#!/bin/sh\nexec \"\$HOME/old/path/devrig\" \"\$@\"\n")
        ensureBinLauncher(home, isWin = false, ownRoot = ownRoot, ownJava = ownJava, userHome = userHome)
        assertTrue(target.readText().contains("binaries/devrig-linux-x64-1.2.3-abc/devrig-1.2.3/bin/devrig"))
    }

    @Test
    fun `missing launcher is recreated`() {
        ensureBinLauncher(home, isWin = false, ownRoot = ownRoot, ownJava = ownJava, userHome = userHome)
        val target = home.binDir.resolve("devrig")
        Files.delete(target)
        ensureBinLauncher(home, isWin = false, ownRoot = ownRoot, ownJava = ownJava, userHome = userHome)
        assertTrue(target.exists())
    }

    // ── ensureBinLauncher core (Windows) ──

    @Test
    fun `windows writes both devrig_ps1 and devrig_cmd`() {
        ensureBinLauncher(home, isWin = true, ownRoot = ownRoot, ownJava = ownJava, userHome = userHome)
        val ps1 = home.binDir.resolve("devrig.ps1")
        val cmd = home.binDir.resolve("devrig.cmd")
        assertTrue(ps1.exists() && cmd.exists(), "both Windows launchers must be written")
        assertTrue(ps1.readText().contains("DEVRIG_JAVA_HOME"))
        assertTrue(ps1.readText().contains("devrig.bat"), "inner launcher must be devrig.bat on Windows")
        assertEquals(renderWindowsCmd(), cmd.readText())
        assertFalse(home.binDir.resolve("devrig").exists(), "no POSIX launcher on the Windows branch")
    }

    // ── guard: do not repoint the launcher when running from a build tree (not under ~/.mcp-steroid) ──

    @Test
    fun `does not self-register when devrig root is outside the mcp-steroid home`() {
        val buildTreeRoot = tmp.resolve("repo").resolve("npx-kt").resolve("build").resolve("install").resolve("devrig")
        ensureBinLauncher(home, isWin = false, ownRoot = buildTreeRoot, ownJava = ownJava, userHome = userHome)
        assertFalse(home.binDir.resolve("devrig").exists(), "build-tree runs must not write a launcher")
    }

    // ── public entry point is best-effort: never throws even when DevrigRoot cannot resolve ──

    @Test
    fun `public ensureBinLauncher never throws when the devrig root is unresolvable`() {
        // Force DevrigRoot.path to throw deterministically: a code-source with no lib/+ij-plugin.zip ancestor.
        DevrigRootTestSupport.overrideCodeSource(tmp.resolve("no-installdist").resolve("classes"))
        assertDoesNotThrow { ensureBinLauncher(home) }
        assertFalse(home.binDir.resolve("devrig").exists(), "nothing should be written when the root is unresolvable")
    }

    // ── cross-module drift guard: the renderers must stay byte-identical (modulo line endings) to the
    //    launcher bodies the generated install.sh / install.ps1 actually write (installer-gen templates),
    //    else a fresh install + self-heal would rewrite on every launch. ──

    @Test
    fun `renderPosixLauncher matches the install_sh_tmpl heredoc body`() {
        val tmpl = repoFile("installer-gen/src/main/resources/templates/install.sh.tmpl").readText()
        val start = tmpl.indexOf("<<EOF\n") + "<<EOF\n".length
        val end = tmpl.indexOf("\nEOF", start)
        require(start > 5 && end > start) { "could not locate the launcher heredoc in install.sh.tmpl" }
        val jdk = "REL/jdk-home"
        val launcher = "REL/bin/devrig"
        // Emulate the unquoted-heredoc expansion: install.sh shell-expands ${jdk_home_rel}/${launcher_rel};
        // \$ becomes a literal $ in the written file.
        val expanded = tmpl.substring(start, end + 1)
            .replace("\${jdk_home_rel}", jdk)
            .replace("\${launcher_rel}", launcher)
            .replace("\\\$", "\$")
        assertEquals(normalizeLauncher(renderPosixLauncher(launcher, jdk)), normalizeLauncher(expanded))
    }

    @Test
    fun `renderWindowsPs1 and renderWindowsCmd match the install_ps1_tmpl bodies`() {
        val tmpl = repoFile("installer-gen/src/main/resources/templates/install.ps1.tmpl").readText()
        val jdk = "REL\\jdk-home"
        val launcher = "REL\\bin\\devrig.bat"

        // devrig.ps1 here-string: PowerShell expands $jdkHomeRel/$launcherRel; backtick-$ becomes literal $.
        val ps1Start = tmpl.indexOf("@\"\n") + "@\"\n".length
        val ps1End = tmpl.indexOf("\n\"@", ps1Start)
        require(ps1Start > 2 && ps1End > ps1Start) { "could not locate the devrig.ps1 here-string in install.ps1.tmpl" }
        val ps1Expanded = tmpl.substring(ps1Start, ps1End)
            .replace("\$jdkHomeRel", jdk)
            .replace("\$launcherRel", launcher)
            .replace("`\$", "\$")
        assertEquals(normalizeLauncher(renderWindowsPs1(launcher, jdk)), normalizeLauncher(ps1Expanded))

        // devrig.cmd $cmd string: decode `r`n -> CRLF and `" -> ".
        val cmdLine = tmpl.lines().first { it.trimStart().startsWith("\$cmd = ") }
        val cmdDecoded = cmdLine.substringAfter("\"").substringBeforeLast("\"")
            .replace("`r`n", "\n")
            .replace("`\"", "\"")
        assertEquals(normalizeLauncher(renderWindowsCmd()), normalizeLauncher(cmdDecoded))
    }

    private fun repoFile(rel: String): File {
        var d: File? = File("").absoluteFile
        while (d != null) {
            if (File(d, "settings.gradle.kts").isFile) return File(d, rel)
            d = d.parentFile
        }
        error("could not locate the repo root (settings.gradle.kts) from ${File("").absolutePath}")
    }
}
