/* Copyright 2025-2026 Eugene Petrenko (mcp@jonnyzzz.com); Copyright 2025-2026 JetBrains. Use of this source code is governed by the Apache 2.0 license. */
package com.jonnyzzz.mcpSteroid.devrig

import java.nio.file.AtomicMoveNotSupportedException
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardCopyOption
import java.nio.file.attribute.PosixFilePermission
import kotlin.io.path.exists
import kotlin.io.path.readText

internal fun isWindows(): Boolean =
    System.getProperty("os.name").lowercase().contains("windows")

/**
 * Self-registration of the user-facing `~/.mcp-steroid/bin` launcher(s).
 *
 * On every `devrig mcp` / `devrig install` startup this ensures `~/.mcp-steroid/bin/devrig` (POSIX) or
 * `devrig.ps1` + `devrig.cmd` (Windows) exists and points at devrig's OWN current installDist location
 * and the JDK it is running under — so the launcher self-heals if it is missing or stale. The launcher
 * content is a byte-for-byte copy of what the generated install.sh / install.ps1 write (see the
 * installer-gen templates), so a fresh install followed by a self-heal produces identical bytes and never
 * ping-pongs. It rewrites ONLY when the content actually changed (normalized comparison), never on every
 * launch.
 *
 * Best-effort: any failure to resolve devrig's root or write the launcher is logged to stderr and
 * swallowed — it must never prevent `devrig mcp` from serving. All output goes to stderr; stdout is the
 * MCP JSON-RPC channel.
 */
fun ensureBinLauncher(home: HomePaths) {
    try {
        ensureBinLauncher(
            home = home,
            isWin = isWindows(),
            ownRoot = DevrigRoot.path,
            ownJava = Path.of(System.getProperty("java.home")).toAbsolutePath().normalize(),
            userHome = Path.of(System.getProperty("user.home")).toAbsolutePath().normalize(),
        )
    } catch (e: Exception) {
        System.err.println("[mcp-steroid] could not (re)write the devrig launcher: $e")
    }
}

/**
 * Testable core — every input is explicit (no environment lookups), so the OS branch and path logic are
 * unit-testable without touching `os.name` / `user.home` / `java.home`.
 */
internal fun ensureBinLauncher(
    home: HomePaths,
    isWin: Boolean,
    ownRoot: Path,
    ownJava: Path,
    userHome: Path,
) {
    // Only self-register when devrig runs from an INSTALLED location under ~/.mcp-steroid (the
    // content-addressed binaries/ dir, or the dev 'devrig/' dir). When devrig runs from a build tree
    // (integration tests, `./gradlew run`), do NOT repoint the user's launcher at a transient dir.
    if (!ownRoot.toAbsolutePath().normalize().startsWith(home.home.toAbsolutePath().normalize())) return

    val ownBin = ownRoot.resolve("bin").resolve(if (isWin) "devrig.bat" else "devrig")
    val launcherRel = relToHome(userHome, ownBin)
    val jdkHomeRel = relToHome(userHome, ownJava)
    if (isWin) {
        writeIfChanged(home.binDir, home.binDir.resolve("devrig.ps1"), renderWindowsPs1(launcherRel, jdkHomeRel), executable = false, ownBin = ownBin)
        writeIfChanged(home.binDir, home.binDir.resolve("devrig.cmd"), renderWindowsCmd(), executable = false, ownBin = ownBin)
    } else {
        writeIfChanged(home.binDir, home.binDir.resolve("devrig"), renderPosixLauncher(launcherRel, jdkHomeRel), executable = true, ownBin = ownBin)
    }
}

/** Byte-exact copy of the POSIX wrapper that install.sh writes (installer-gen install.sh.tmpl heredoc). */
internal fun renderPosixLauncher(launcherRel: String, jdkHomeRel: String): String =
    "#!/bin/sh\n" +
        "# devrig launcher — generated by install.sh. Writes nothing to stdout (MCP stdio channel).\n" +
        "# Sets DEVRIG_JAVA_HOME (honored by the devrig launcher) to the bundled JDK unless the user\n" +
        "# already provided one, then hands off to the devrig binary.\n" +
        "if [ -z \"\${DEVRIG_JAVA_HOME:-}\" ]; then\n" +
        "  DEVRIG_JAVA_HOME=\"\$HOME/$jdkHomeRel\"; export DEVRIG_JAVA_HOME\n" +
        "fi\n" +
        "exec \"\$HOME/$launcherRel\" \"\$@\"\n"

/** Byte-exact copy of devrig.ps1 that install.ps1 writes (installer-gen install.ps1.tmpl here-string). */
internal fun renderWindowsPs1(launcherRel: String, jdkHomeRel: String): String =
    "# devrig launcher — generated by install.ps1. Writes nothing to stdout (MCP stdio channel).\n" +
        "# Sets DEVRIG_JAVA_HOME (honored by the devrig launcher) to the bundled JDK unless already set.\n" +
        "\$root = \$env:USERPROFILE; if (-not \$root) { \$root = \$env:HOME }\n" +
        "if (-not \$env:DEVRIG_JAVA_HOME) { \$env:DEVRIG_JAVA_HOME = Join-Path \$root '$jdkHomeRel' }\n" +
        "& (Join-Path \$root '$launcherRel') @args\n" +
        "exit \$LASTEXITCODE\n"

/** Constant devrig.cmd shim that install.ps1 writes — finds devrig.ps1 via %~dp0, no embedded paths. */
internal fun renderWindowsCmd(): String =
    "@echo off\r\n" +
        "powershell.exe -NoProfile -ExecutionPolicy Bypass -File \"%~dp0devrig.ps1\" %*\r\n"

private fun writeIfChanged(dir: Path, target: Path, desired: String, executable: Boolean, ownBin: Path) {
    // An unreadable existing launcher (non-UTF-8 bytes, wrong file type, transient IO) counts as
    // "changed" so a corrupt launcher self-heals rather than being left in place.
    val current = if (!target.exists()) null else try {
        target.readText()
    } catch (e: Exception) {
        System.err.println("[mcp-steroid] existing launcher $target is unreadable ($e); rewriting it")
        null
    }
    if (current != null && normalizeLauncher(current) == normalizeLauncher(desired)) return
    writeAtomically(dir, target, desired, executable)
    System.err.println("[mcp-steroid] (re)wrote $target -> $ownBin")
}

/** Tolerant of CRLF↔LF and trailing-newline differences so we rewrite ONLY on a real content change. */
internal fun normalizeLauncher(s: String): String = s.replace("\r\n", "\n").trimEnd('\n')

/** Relative to the OS user home, no leading separator; fails fast if [target] is not under [userHome]. */
internal fun relToHome(userHome: Path, target: Path): String {
    val rel = userHome.relativize(target.toAbsolutePath().normalize())
    require(rel.nameCount > 0 && !rel.startsWith("..")) {
        "cannot place launcher: $target is not under the user home $userHome"
    }
    return rel.toString()
}

private fun writeAtomically(dir: Path, target: Path, content: String, executable: Boolean) {
    Files.createDirectories(dir)
    val tmp = dir.resolve(".tmp.${ProcessHandle.current().pid()}.${target.fileName}")
    Files.writeString(tmp, content)
    // Set the executable bit on the staging file BEFORE the move, so the final launcher is never
    // momentarily non-executable (mirrors install.sh: chmod +x then mv).
    if (executable) setExecutable(tmp)
    try {
        Files.move(tmp, target, StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING)
    } catch (e: AtomicMoveNotSupportedException) {
        System.err.println("[mcp-steroid] atomic move unsupported (${e.message}); using a plain move")
        Files.move(tmp, target, StandardCopyOption.REPLACE_EXISTING)
    }
}

private fun setExecutable(file: Path) {
    try {
        val perms = Files.getPosixFilePermissions(file).toMutableSet()
        perms += PosixFilePermission.OWNER_EXECUTE
        perms += PosixFilePermission.GROUP_EXECUTE
        perms += PosixFilePermission.OTHERS_EXECUTE
        Files.setPosixFilePermissions(file, perms)
    } catch (e: UnsupportedOperationException) {
        // Non-POSIX filesystem (e.g. Windows): fall back to the File API.
        System.err.println("[mcp-steroid] POSIX permissions unsupported (${e.message}); using File.setExecutable")
        file.toFile().setExecutable(true, false)
    }
}
